travis:
  secure:
    BINSTAR_TOKEN: WukAZqZOZyQniOzMQmTqlRFVscgT/VF4eINACU5C9pkjUpoayODN1S+aO2ZprliiKHOryNtsWsELihJQd0dOkldzrmNHlYooa9HARRXs+i72XEEuJWPZePsXhMnNTzSM3WOtr5BKCcviiUveKXT9UXQFl5X7UmaWFEAeIg8jy6NgL1BEsoOL6MEEKsPwwNHby+QZjdJ+3wOYviLe0OKo87QsAZVN/1ljFQ38Nn6Fvke+7ZPqFByQfRF6P+/ypwNVyYJhTM4Kb9j7iKtAnXVLmeIh0sSxTQgCJlZNum3EtZ76UdGTo4XvuZaY1BPQ98h3Ou/8buqFgcmGyWu5TvxidROX2sPL1iNBu/hfXUc14ISs3PmJJQu5V4wd/PUDGHqf2eeKjOnUfyNhRSU6cTpBfQsrpMYKfsflTOAArL/fsXqPqTqPLtkqJ6u0ax+dxFtXxiZxNqaR87oktIAzYfpDwgDJ2rH+a+5dS3f3/P6N7NZL3JdPkYRy07bDPGUlM6fOPlRgEY8l42AfdtZc/iqvIITskPp1eG7UHXlysXuJYW8mUWHElkQVmsIE+krpI0b4Tsja5MDB8UfOyrQkxKob9vzp72N/esH1/LzTNwGAfrNQO7CFrKDeoXaghHhkhM3rMrvMEtbCWar7a1Mff50yZqA+hguhTmNQ73JwEtZqH5M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
