travis:
  secure:
    BINSTAR_TOKEN: RsApwDFl3804gfHvv9VuR3kO9gGfE920+96twdrqe+/gCA/DcC78nlNDeRGG/Ekqv81bHSMX23eUt6KU1jXG6GYtOAkNF94t9gOD6oGaGMqEVQSdKW6xP2Q4rhgyfSEwGbn7VQtbjvyEhZbjamn08NDKegOOvr9JL5N3W4HMv8UL+Yx/TIh9csxF8/Ra9o5db4499fR391Ymm7/RbHeMP7TeGNNhVYHFazyplvsZAZLYR+By3Mkc0aorSv7yoU9y/LZPLNMVmW16UUtc1WAcQOHbyzdql2xds36384FNR+OWijvwwKpXsKH22XutmeAHTAqASJpWFkkR+II7CvwFfcC18v5birKhFxCGwAb9Tsh7RQ+/w5ul1KnVSUdpc0HcqTOLwtr0/hhBBDGpZqK8RfOGgA96rdHY8HD0i5Q62u4pEbADxn/OHYvlrmKN5oKam4o7ipas/jT0tEiD6B61QoB2yhsi988agG9MY8RLQ7xFg6Km0Wj77+sFF9la7CJPLZ1ZetVTxS2EMl5LJgZZB9bHRUFcfmrP2DaZxqm3Vs4ctgnF0eMwER3C7ItTd6+xURU4Of48PM3JxEvBXpAtQ/gjhwPJlqXGwlHONyzz6VgPlWWI4IcliGhtN740fdr63w9iFyOXk/qo/usRl2iFGojazR34uuIav1PFYX2Dpbs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
