travis:
  secure:
    BINSTAR_TOKEN: Wc27BfNtLVzAvBI724Wd6fc9j/Y8h9/MtGhHRSIiVCINlBeP2/a4yx0r/TvzOKbeX0dWgt5fRCNTxq100NoPwbrPaz+wSUIHcIBuL5BvSCxFQc0074EPlXf4V4PvxIl3MHDpATbJsrImpQhmvNNgPzVJw5fhV/R+cdkJtoDX5VpyUdQ62rQOoZMol18nhWYCgdZt90vEKcxOEW0Us87Pbl6HEMRpN5TM2aZzNOg6YxQMPj/D3o8m8fJWhyO30iMyNkirc352yAprUxDwqGsOBE25XZomTcG9r5xY5vDtywRj2z7Eyy0rnkYE4Tce5Wn+8cmbWoVNBMJd0y0WyWbenXjt0SBe+C1NhuG7tKtnv28EDsd/sP0PulxZypbcynp20GxooCS1aN177Bpse7v19HYmwz84GJffKXxp4VWfLIxrJ7jfHe9ircIuWVS3WHO5RXuMlhrI3WrJk2aku8/R+8rCYiyU1znqQBSM96UL3O9M36APKm126j+KgpPDoVQbnVBA2Sdt3v8dR5+xlsMWlT53TxjzOOlcro+L4Pq450TAUihj+22SED/kO9zE8ZFDMUODNnsb1AutDqLt7vxLKOSYgqJmjldrDjcRJXPjDCznup5JmDp45Pz0ATLR4WUcC48ZCC1rCLPRSilWgVMKRJI8tk8EAt5VPezNbKSPsxI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
