travis:
  secure:
    BINSTAR_TOKEN: Bk1n8gKr1VtmoqXvUS06yBR7GlnjEUF4TVujbonL6KAE8gYs0bwK1Vu4xucUpo0Dwhu899oqQvsrPsZRomUu/ABJ/p9AqkH/w35lNG8MDUh4QV2QGM7siZR7xcUAqlOslACGzlcx/Lr9Xh49GA12x9EFwvKVhpRDF/4ykbvsWHpt6Z8OHIm84EDcbME4wCesDl+HTDWt/l0bpCwFQVRlpXFqG1tgdBIjJVkEeAxpY1OUJun6mo2ZxHuY8o+q1syyMFl3riHE+dbTqO6slgoWdpl54p9wJLWh1YBf8/eRtabQx+8NX50K1mdcBQHCIO6ivF45Ng+bC9ocxbsL7T1WLIUn/W6tBlFV3Jnf7XNV0MLK6wdhjt5Ns20igEKARYtyhvfhMTGef3wmzQmCL1sl+vcjBaN3ngk/QTfYuHulMiwRg8HVtRakY6VJIejSqf+B17mt679f6be09F8cbwcCTuHSvF1L76ICdMEosAzsP+TW8AdsXCksXLoYlse0C5F/KLm9OgfDiWEyVToRzlB0lE102wFaizoZL+fO/YNumx81usPd9XIw+WPuTETmWeSPRn1YDhrIweyYTKz4aCZe4S17St5yR9Wr0Keb1G6Qfb8fLAz1Jt7Dk0OHiX1VxA5DzcqwUP2K24gWe/RWf1+UQx7zNNIqhwfGvLRCevKDfQ0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
